language: php

php:
  - 7.1

matrix:
  fast_finish: true

  include:
    - php: 7.1
      env: COMPOSER_FLAG=--prefer-lowest
    - php: 7.1
      env: COMPOSER_FLAG=--prefer-stable

script:
  # Composer
  - travis_retry composer install --no-interaction

sudo: false

cache:
  directories:
    - $HOME/.composer/cache
